services:
  postgres:
    image: postgres:15.9
    container_name: pr-allocation-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pr_allocation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pr-allocation-service:
    build: .
    container_name: pr-allocation-service
    ports:
      - "8080:8080"
    environment:
      ENV: ${ENV:-dev}
      SERVER_HOST: ${SERVER_HOST:-localhost}
      SERVER_PORT: ${SERVERPORT:-8080}

      # Database Configuration
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-pr_allocation}
      DATABASE_SSLMODE: ${DATABASE_SSLMODE:-disable}

      # Config path
      CONFIG_PATH: ${CONFIG_PATH:-./config}


    depends_on:
      - postgres

volumes:
  postgres_data:

