services:
  postgres:
    image: postgres:15.9
    container_name: pr-allocation-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pr_allocation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pr-allocation-service:
    build: .
    container_name: pr-allocation-service
    ports:
      - "8080:8080"
    env_file:
      - ./config/.env
    depends_on:
      - postgres

volumes:
  postgres_data:

