env: development

server:
  host: "0.0.0.0"
  port: "8082"

services:
  pr_allocation:
    host: "pr-allocation-service"
    port: "8080"
  code_storage:
    host: "code-storage-service"
    port: "8081"

